# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(max_length=200),
        ),
    ]
